### ISSUE TITLE
Datetimes are not parsed correctly

### ISSUE THREAD

**Issue by dmyersturnbull** [jvican/stoml#3]
Neither of these work:
- 2016-11-27T14:30:30
- 2016-11-27T14:30:30.153-08:00

**Comment by jvican** [comment]
Hey @dmyersturnbull, thanks for reporting! I really welcome a PR fixing this, so let me know if you need any guidance. :smile:

**Comment by nicosuave** [comment]
I'll take this one ✋. I'm working on supporting all the formats listed in https://github.com/toml-lang/toml#offset-date-time

**Comment by jvican** [comment]
@nicosuave That would be awesome. Just added you as a collaborator to this repo. Open a PR when you're done! :smile:.

**Comment by tindzk** [comment]
@nicosuave Are you still working on it? I [implemented](https://github.com/sparsetech/toml-scala/blob/master/jvm/src/main/scala/toml/PlatformRules.scala) the date and time formats using `java.time` and would be happy to submit a pull request.

**Comment by jvican** [comment]
@tindzk I think he's not, feel fre to do it :smile:

**Comment by nicosuave** [comment]
All you, @tindzk
